
import type { Character } from './types';

export const CHARACTER_ROSTER: Character[] = [
  { name: 'Adam Warlock' },
  { name: 'Black Panther' },
  { name: 'Black Widow' },
  { name: 'Captain America' },
  { name: 'Cloak & Dagger' },
  { name: 'Doctor Strange' },
  { name: 'Emma Frost' },
  { name: 'Groot' },
  { name: 'Hawkeye' },
  { name: 'Hela' },
  { name: 'Hulk' },
  { name: 'Human Torch' },
  { name: 'Invisible Woman' },
  { name: 'Iron Fist' },
  { name: 'Iron Man' },
  { name: 'Jeff the Land Shark' },
  { name: 'Loki' },
  { name: 'Luna Snow' },
  { name: 'Magik' },
  { name: 'Magneto' },
  { name: 'Mantis' },
  { name: 'Mister Fantastic' },
  { name: 'Moon Knight' },
  { name: 'Namor' },
  { name: 'Peni Parker' },
  { name: 'Phoenix' },
  { name: 'Psylocke' },
  { name: 'The Punisher' },
  { name: 'The Thing' },
  { name: 'Rocket Raccoon' },
  { name: 'Scarlet Witch' },
  { name: 'Squirrel Girl' },
  { name: 'Spider-Man' },
  { name: 'Star-Lord' },
  { name: 'Storm' },
  { name: 'Thor' },
  { name: 'Ultron' },
  { name: 'Venom' },
  { name: 'Winter Soldier' },
  { name: 'Wolverine' },
].sort((a, b) => a.name.localeCompare(b.name));

export const PLAYER_CONFIG = {
  N: {
    name: "Niko",
    color: "cyan",
    textColor: "text-cyan-400",
    borderColor: "border-cyan-400",
    buttonClasses: "bg-cyan-500/20 border-cyan-500 hover:bg-cyan-500/40 hover:text-cyan-300",
    glow: "text-glow-cyan",
    slotShadow: "slot-shadow-cyan",
  },
  S: {
    name: "Safwan",
    color: "orange",
    textColor: "text-orange-400",
    borderColor: "border-orange-400",
    buttonClasses: "bg-orange-500/20 border-orange-500 hover:bg-orange-500/40 hover:text-orange-300",
    glow: "text-glow-orange",
    slotShadow: "slot-shadow-orange",
  }
};
